### PR TITLE
Add Dockerfile & docker-compose to run gitreports rails app

### PR DESCRIPTION
**Pull request by apfrod**
Adds Dockerfile to build and run the rails app and docker-compose.yml for redis, postgres and sidekiq process to run the whole thing.

for thermeon/issues#98

### CODE REVIEW

**Comment by gbjk** [comment]
@apfrod Not yet assigned to anyone, FWIW.

**Comment by apfrod** [comment]
I don't think we'll be using the docker-compose.yml but it's handy anyway.

**Comment by gbjk** [comment]
I'm confused. What's the final daemon that actually gets run, though?
Shouldn't we have an entrypoint or exec or something rather than just another RUN ?

**Comment by apfrod** [comment]
it's run in the docker-compose, or the marathon cmd. I've not put it in the dockerfile because there's two; one for rails and one for the daemon, and more for eg running rake to set up the db

**Comment by gbjk** [comment]
So I think you want:
Dockerfile.build
Dockerfile
Dockerfile.deploy

**Comment by apfrod** [comment]
Yes that would be cleaner, but I don't think it helps me run it, and doesn't solve having to run another for sidekiq.

**Comment by gbjk** [comment]
I think it still stands, though, right?

My thing is: docker build should always give you a container that you run for the primary app, and anything that isn't that should be sub-named to make it clear what it's for.

**Comment by apfrod** [comment]
I followed https://docs.docker.com/compose/rails/ and it doesn't do what you suggest.

We're not going to use this now anyway, and it works as it stands.

**Pull request closed without merging**
